export const elevenLabsVoices = {
  en: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (English)
  fr: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (French)
  es: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Spanish)
  de: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (German)
  it: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Italian)
  pt: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Portuguese)
  nl: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Dutch)
  sv: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Swedish)
  da: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Danish)
  no: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Norwegian)
  fi: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Finnish)
  pl: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Polish)
  ru: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Russian)
  tr: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Turkish)
  ar: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Arabic)
  hi: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Hindi)
  ja: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Japanese)
  ko: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Korean)
  zh: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Chinese)
  ct: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Cantonese)
  gu: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Gujarati)
  vi: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Vietnamese)
  pa: "beg1N23VnJbirmY9S6gO",     // Cloned Multilingual (Punjabi)
  th: "beg1N23VnJbirmY9S6gO"      // Cloned Multilingual (Thai)
};
