export const elevenLabsVoices = {
  en: "pNInz6obpgDQGcFmaJgB",     // Adam (English)
  fr: "EXAVITQu4vr4xnSDxMaL",     // Bella (French)
  es: "VR6AewLTigWG4xSOukaG",     // Arnold (Spanish)
  de: "AZnzlk1XvdvUeBnXmlld",     // Domi (German)
  it: "EXAVITQu4vr4xnSDxMaL",     // Bella (Italian - using same as French)
  pt: "VR6AewLTigWG4xSOukaG",     // Arnold (Portuguese - using same as Spanish)
  nl: "AZnzlk1XvdvUeBnXmlld",     // Domi (Dutch - using same as German)
  sv: "pNInz6obpgDQGcFmaJgB",     // Adam (Swedish - using same as English)
  da: "pNInz6obpgDQGcFmaJgB",     // Adam (Danish - using same as English)
  no: "pNInz6obpgDQGcFmaJgB",     // Adam (Norwegian - using same as English)
  fi: "pNInz6obpgDQGcFmaJgB",     // Adam (Finnish - using same as English)
  pl: "AZnzlk1XvdvUeBnXmlld",     // Domi (Polish - using same as German)
  ru: "AZnzlk1XvdvUeBnXmlld",     // Domi (Russian - using same as German)
  tr: "AZnzlk1XvdvUeBnXmlld",     // Domi (Turkish - using same as German)
  ar: "AZnzlk1XvdvUeBnXmlld",     // Domi (Arabic - using same as German)
  hi: "AZnzlk1XvdvUeBnXmlld",     // Domi (Hindi - using same as German)
  ja: "AZnzlk1XvdvUeBnXmlld",     // Domi (Japanese - using same as German)
  ko: "AZnzlk1XvdvUeBnXmlld",     // Domi (Korean - using same as German)
  zh: "AZnzlk1XvdvUeBnXmlld",     // Domi (Chinese - using same as German)
  ct: "AZnzlk1XvdvUeBnXmlld",     // Domi (Cantonese - using same as German)
  gu: "AZnzlk1XvdvUeBnXmlld",     // Domi (Gujarati - using same as German)
  vi: "AZnzlk1XvdvUeBnXmlld",     // Domi (Vietnamese - using same as German)
  pa: "AZnzlk1XvdvUeBnXmlld",     // Domi (Punjabi - using same as German)
  th: "AZnzlk1XvdvUeBnXmlld"      // Domi (Thai - using same as German)
};
